---
title: "About"
image: "/images/team/swilgosz-small"
---

### About

<Grid container spacing={2}>
  <Grid item xs={12} md={6}>
  <Typography paragraph>Hi, I'm <strong>Seb Wilgosz</strong>, and I run <a href='https://hanamimastery.com'>HanamiMastery</a> to help you get into <a href='https://hanamirb.org/'>Hanami framework</a> as easily as possible.</Typography>

  <Typography paragraph>Among the others, I am an author of <a href='https://www.udemy.com/course/ruby-on-rails-api-the-complete-guide/' target='_blank'>Rails API course</a> on Udemy and <a href='https://driggl.com' target='_blank'>Driggl blog</a>.</Typography>
</Grid>
  <Grid item xs={12} md={6}>
  <img alt='Sebastian Wilgosz' src='/images/team/swilgosz-small.jpg' />
  </Grid>
</Grid>

<br />

I love Ruby, so **I'd love to see the Ruby ecosystem evolving and changing**. This is why Hanami Mastery came alive!

### Mission

#### Make Open Source projects a good place for full-time jobs.

I strongly believe that great community projects should get more support and financial stability. Unfortuantely, most of amazing people who create great libraries and projects, need to work during nights and over the weekends **to make OUR lives better**.

[HanamiMastery](https://hanamimastery.com) is a first step, to improve on that field.

#### Rules

This project is driven by a few simple rules.

- **10% of all income generated by this project and activity goes to support Hanami development since day one**.
- This includes Github sponsoring of my account, Youtube Channel, Blog monetization, and so on.
- As soon as the Hanami 2.0 is released, we'll publish at least one episode per week.

#### Episodes

Episode consists (or will be) of:

- Article guide
- Summary notes/snippets (comming soon)
- Youtube Video guide (need support to get there)


### Do you like this idea? Consider support!

If you like this project and the idea behind it, ** support me on Github**!

The more support I get, the more time I'll be able to put into creating great content for you and the bigger quality it'll have!

I especially need a support for recording regular Youtube Videos.


### Follow us!

- Twitter: [@hanamimastery](https://twitter.com/hanamimastery) | [@sebwilgosz](https://twitter.com/sebwilgosz)
- Youtube Channel: [Hanami Mastery](https://www.youtube.com/channel/UC4Z5nwSfZrUO4NI_n9SY3uQ)
- Github: [@hanamimastery](https://github.com/hanamimastery) | [@swilgosz](https://github.com/swilgosz)
- FB: [HanamiMastery](https://facebook.com/hanamimastery)
